Repository divanov11/Mumble, pull requests merged in 2021-05, with the labels that each got.

#346 Introducing the Reviewers in MUMBLE Repo
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  REQUIREMENTS.md
  Reviewers.md
  images/dark-logo.png
Labels: Status : Needs 1 Review, feature

#370 🔥 Sidebar Navigations
  frontend/src/Routes.js
  frontend/src/components/CreatePost.js
  frontend/src/components/FeedCard.js
  frontend/src/components/Header.js
  frontend/src/components/Page.js
  frontend/src/components/PostCard.js
  frontend/src/components/SidebarNav.js
  frontend/src/components/index.js
  frontend/src/pages/ArticlePage.js
  frontend/src/pages/CreateArticlePage.js
  frontend/src/pages/CreateDiscussionPage.js
  frontend/src/pages/DiscussionPage.js
  frontend/src/pages/HomePage.js
  frontend/src/pages/NotificationsPage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/pages/SearchPage.js
  frontend/src/pages/UserSettingsPage.js
  frontend/src/styles/common/_animation.css
  frontend/src/styles/common/_card.css
  frontend/src/styles/common/_layout.css
  frontend/src/styles/common/_page.css
  frontend/src/styles/common/_utilities.css
  frontend/src/styles/common/_variables.css
  frontend/src/styles/components/Feed.css
  frontend/src/styles/components/HeaderBar.css
  frontend/src/styles/components/SidebarNav.css
  frontend/src/styles/index.css
Labels: enhancement, feature

#368 Disabled button and added a loader in login/register #351
  frontend/src/common/Button.js
  frontend/src/components/LoginForm.js
  frontend/src/components/SignupForm.js
  frontend/src/reducers/auth.js
  frontend/src/styles/common/_button.css
Labels: enhancement, feature

#369 implemented deleting mumble/ remumble (#363)
  frontend/src/actions/postActions.js
  frontend/src/actions/userActions.js
  frontend/src/components/PostCard.js
  frontend/src/components/PostCardOptions.js
  frontend/src/constants/userConstants.js
  frontend/src/reducers/postReducers.js
  frontend/src/reducers/userReducers.js
Labels: enhancement, feature

#376 Edited the placeholder in Modal Settings (Fix #375)
  frontend/src/components/UserSettingUpdateModal.js
Labels: Status : Needs 2 Reviews, bug

#377 working on the articles page
  frontend/src/Routes.js
  frontend/src/actions/articleActions.js
  frontend/src/components/SearchByArticlesList.js
  frontend/src/constants/articleConstants.js
  frontend/src/pages/ArticlesPage.js
  frontend/src/pages/index.js
  frontend/src/reducers/articleReducer.js
  frontend/src/reducers/userReducers.js
Labels: Status : Needs 1 Review, enhancement

#385 fixed #383 - Refresh Token Logic
  frontend/src/App.js
  frontend/src/actions/authActions.js
  frontend/src/constants/authConstants.js
  frontend/src/reducers/auth.js
  frontend/src/services/authService.js
  frontend/src/store.js
Labels: enhancement

#393 Working on Follow / Unfollow Logic
  frontend/src/App.js
  frontend/src/actions/userActions.js
  frontend/src/components/FollowButton.js
  frontend/src/components/LoginForm.js
  frontend/src/components/PostCardOptions.js
  frontend/src/components/SignupForm.js
  frontend/src/components/UserCard.js
  frontend/src/constants/userConstants.js
  frontend/src/reducers/auth.js
  frontend/src/reducers/index.js
  frontend/src/reducers/userReducers.js
  frontend/src/services/usersService.js
  frontend/src/store.js
Labels: bug, enhancement

#408 #407 - hide discussions in UI
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/SidebarNav.js
  frontend/src/pages/ArticlesPage.js
  frontend/src/pages/CreateDiscussionPage.js
  frontend/src/pages/DiscussionPage.js
  frontend/src/pages/HomePage.js
Labels: enhancement
