Repository divanov11/Mumble, pull requests merged in 2021-04, with the labels that each got.

#92 Clean Up - adding a react eslint plugin to catch jsx errors
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Modal.js
  frontend/src/Pages/Discussion.js
  frontend/src/ui-kit/scripts/app.js
Labels: enhancement

#50 Added React Build GitHub action
  .github/workflows/node.js.yml
  frontend/src/App.test.js
Labels: enhancement

#134 Toggle Discussions in feed
  frontend/src/common/PostAction.js
  frontend/src/common/PostCard.js
  frontend/src/components/Feed.js
  frontend/src/data/posts.js
  frontend/src/styles/components/Feed.css
  frontend/src/styles/components/Modal.css
Labels: Status: Dennis Feedback Needed

#135 Fail the build if prettier wasn't ran
  .github/workflows/node.js.yml
  frontend/package.json
Labels: Status: Needs Review

#137 linking notifications to actual content
  frontend/src/components/Header.js
  frontend/src/data/notifications.js
Labels: Status: Needs Review

#148 Created and Styled 💐 Notification page
  frontend/src/App.js
  frontend/src/data/notifications.js
  frontend/src/pages/NotificationsPage.js
  frontend/src/styles/components/Notification.css
Labels: Status: Dennis Feedback Needed

#142 Added Create Discussion Route
  frontend/src/App.js
  frontend/src/components/DiscussionsCard.js
  frontend/src/pages/CreateDiscussionPage.js
  frontend/src/styles/components/CreateDiscussionPage.css
Labels: Status: Dennis Feedback Needed

#149 Fixing Nested Comments
  frontend/src/common/PostCard.js
  frontend/src/components/Feed.js
  frontend/src/data/posts.js
Labels: Status: Dennis Feedback Needed, Status: Needs Review

#151 Add requirements section to run and develop in the project
  README.md
  frontend/README.md
Labels: Status: Unresolved Comments

#152 Scroll Restore on Route path change
  frontend/src/App.js
  frontend/src/common/RestoreScroll.js
  frontend/src/components/Modal.js
  frontend/src/index.js
  frontend/src/pages/SearchPage.js
  frontend/src/styles/common/_base.css
Labels: Status: Unresolved Comments

#160 Login page
  frontend/src/App.js
  frontend/src/components/LoginForm.js
  frontend/src/components/SignupForm.js
  frontend/src/pages/LoginOrSignupPage.js
  frontend/src/pages/LoginPage.js
  frontend/src/styles/components/LoginOrSignUp.css
Labels: Status: Dennis Feedback Needed, Status: On Hold

#184 Scroll bar style improvements.
  frontend/src/styles/App.css
Labels: Status: On Hold, Type: UX / Design

#174 Private Route & Redux Setup
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/constants/authConstants.js
  frontend/src/reducers/auth.js
  frontend/src/reducers/index.js
  frontend/src/store.js
  frontend/src/utilities/PrivateRoute.js
Labels: Status: Dennis Feedback Needed, Status: On Hold
