Repository divanov11/Mumble, pull requests merged in 2021-06, with the labels that each got.

#430 Logout confirmation feature
  frontend/src/App.js
  frontend/src/components/Header.js
  frontend/src/pages/LogoutConfirmation.js
  frontend/src/pages/index.js
  frontend/src/styles/components/LogoutConfirmation.css
Labels: enhancement, feature

#438 Fixed some UI Bugs
  frontend/src/pages/Error404Page.js
  frontend/src/pages/Error500Page.js
  frontend/src/pages/ForgotPasswordPage.js
  frontend/src/pages/LogoutConfirmation.js
  frontend/src/styles/components/Error404Page.css
  frontend/src/styles/components/ForgotPasswordPage.css
  frontend/src/styles/components/LoginOrSignUp.css
Labels: bug

#453 Fixing images so we can run the app locally
  frontend/src/common/Button.js
  frontend/src/components/Contributors.js
  frontend/src/components/Header.js
  frontend/src/components/Notification.js
  frontend/src/components/PostCard.js
  frontend/src/components/SearchByUsersList.js
  frontend/src/components/UserCard.js
  frontend/src/pages/DiscussionPage.js
  frontend/src/pages/UserSettingsPage.js
  frontend/src/styles/common/_button.css
  frontend/src/utilities/getImageUrl.js
Labels: Status: On Hold

#457 fixed the problem of overflow in login/forgotpwd page for smaller devices
  frontend/src/pages/ForgotPasswordPage.js
  frontend/src/styles/components/ForgotPasswordPage.css
  frontend/src/styles/components/LoginOrSignUp.css
Labels: Status: On Hold
